# Generated by Django 5.0.6 on 2024-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_secret_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payer_account_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Учетный номер плательщика'),
        ),
    ]
