PAYER_ACCOUNT_NUMBER_MAX_LEN = 32
FIRST_NAME_MAX_LEN = LAST_NAME_MAX_LEN = PATRONYMIC_MAX_LEN = 30
FIRST_NAME_MIN_LEN = LAST_NAME_MIN_LEN = PATRONYMIC_MIN_LEN = 1
FIO_REGEX = r'[а-яА-ЯЁё-]+'
PASSWORD_MAX_LEN = 30
PASSWORD_MIN_LEN = 8
SECRETWORD_MAX_LEN = 30
SECRETWORD_MIN_LEN = 1
CONFIRM_CODE_EXPIRATION_TIME_MIN = 5
ADDRESS_MAX_LEN = 200
CATEGOTY_NAME_MAX_LEN = PRODUCT_NAME_MAX_LEN = SERVICE_NAME_MAX_LEN = 500
PRODUCT_DESCRIP_MAX_LEN = SERVICE_DESCRIP_MAX_LEN = 1000
