PAYER_ACCOUNT_NUMBER_MAX_LEN = 32
FIRST_NAME_MAX_LEN = LAST_NAME_MAX_LEN = PATRONYMIC_MAX_LEN = 30
FIRST_NAME_MIN_LEN = LAST_NAME_MIN_LEN = PATRONYMIC_MIN_LEN = 1
FIO_REGEX = r'[а-яА-ЯЁё-]+'
PASSWORD_MAX_LEN = 30
PASSWORD_MIN_LEN = 8
SECRETWORD_MAX_LEN = 30
SECRETWORD_MIN_LEN = 1
