# Generated by Django 5.0.6 on 2024-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_avatar_productimage_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'default_related_name': 'photos', 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование категории товара'),
        ),
    ]
