# Generated by Django 5.0.6 on 2024-08-24 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(upload_to='products_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
