# Generated by Django 5.0.6 on 2024-08-24 18:04

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(upload_to=products.models.product_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
